MvcNetCoreZapatillas/Models/ErrorViewModel.cs
namespace MvcNetCoreZapatillas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCoreZapatillas/Models/ImagenZapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcNetCoreZapatillas.Models
{
    [Table("IMAGENESZAPASPRACTICA")]
    public class ImagenZapatilla
    {
        [Key]
        [Column("IDIMAGEN")]
        public int IdImagen { get; set; }
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
    }
}

MvcNetCoreZapatillas/Models/VistaZapatillasImagenes.cs
namespace MvcNetCoreZapatillas.Models
{
    public class VistaZapatillasImagenes
    {

    }
}

MvcNetCoreZapatillas/Models/Zapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcNetCoreZapatillas.Models
{
    [Table("ZAPASPRACTICA")]
    public class Zapatilla
    {
        [Key]
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }
        [Column("PRECIO")]
        public int Precio { get; set; }
    }
}

MvcNetCoreZapatillas/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreZapatillas.Models;
using System.Diagnostics;

namespace MvcNetCoreZapatillas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCoreZapatillas/Controllers/ZapatillasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using MvcNetCoreZapatillas.Models;
using MvcNetCoreZapatillas.Repositories;

namespace MvcNetCoreZapatillas.Controllers
{
    #region PROCEDURES
   /* CREATE PROCEDURE SP_ZAPATILLAS(@POSICION INT)
    AS

        SELECT* FROM(SELECT CAST(ROW_NUMBER() OVER(ORDER BY IDPRODUCTO) AS INT) AS POSICION, IDPRODUCTO, NOMBRE, PRECIO FROM ZAPASPRACTICA) AS QUERY

        WHERE QUERY.POSICION >= @POSICION AND QUERY.POSICION<(@POSICION)
    GO*/
    #endregion
    public class ZapatillasController : Controller
    {
        private RepositoryZapatillas repo;

        public ZapatillasController(RepositoryZapatillas repo)
        {
            this.repo = repo;
        }

        public IActionResult GetZapatillas()
        {
            List<Zapatilla> zapatillas = this.repo.GetZapatillas();
            return View(zapatillas);
        }

        
        public IActionResult DetallesZapatillas(int idZapatilla)
        {
            return View(repo.GetZapatillaDetalle(idZapatilla));
        }

        public IActionResult FotosZapatilla(int idZapatilla)
        {
            List<ImagenZapatilla> imagenes = this.repo.GetImagenesZapatillaId(idZapatilla);
            return View(imagenes);
        }

        //EN INDEX ES DONDE VOY A INTEGRAR LAS PETICIONES ASINCRONAS
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult _ZapatillasPartial()
        {
            List<Zapatilla> zapatillas = this.repo.GetZapatillas();
            //Devolvemos partialView ya que estamos usando ajax
            return PartialView("_ZapatillasPartial", zapatillas);
        }
        
    }
    
   /* f*/
}

MvcNetCoreZapatillas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcNetCoreZapatillas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreZapatillas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCoreZapatillas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://static.vecteezy.com/system/resources/thumbnails/010/994/412/small/nike-logo-black-with-name-clothes-design-icon-abstract-football-illustration-with-white-background-free-vector.jpg"
                    style="width: 60px"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapatillas" asp-action="GetZapatillas">ZAPATILLAS</a>
                        </li>
  
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcNetCoreZapatillas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcNetCoreZapatillas/Views/Zapatillas/DetallesZapatillas.cshtml
@model Zapatilla

<h1 style="color:chartreuse">DETALLES</h1>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">@Model.Nombre</h5>
    <p class="card-text">@Model.Descripcion</p>
    <h6 class="card-subtitle mb-2 text-muted">@Model.Precio</h6>
    <a  asp-controller="Zapatillas" asp-action="FotosZapatilla" asp-route-idZapatilla="@Model.IdProducto">Ver fotos: </a>
  </div>
</div>

MvcNetCoreZapatillas/Views/Zapatillas/FotosZapatilla.cshtml
@model List<ImagenZapatilla>

<h1>FOTOS</h1>
<div class="card ">
    @foreach (ImagenZapatilla imag in Model)
    {
        <img src="@imag.Imagen" style="width:100px"/>
    }
</div>

MvcNetCoreZapatillas/Views/Zapatillas/GetZapatillas.cshtml
@model List<Zapatilla>


    <ul class="list-group">
        @foreach (Zapatilla zap in Model)
    {

        <li class="list-group-item">
          <a asp-controller="Zapatillas" asp-action="DetallesZapatillas"   asp-route-idZapatilla="@zap.IdProducto" style="color:red">PRUEBA @zap.Nombre</a>  
        </li>

        <li class="list-group-item">
          <a asp-controller="Zapatillas" asp-action="GetZapatillas" style="color:green">CORRECTO @zap.Nombre</a>  
        </li>
    }
        
    </ul>

MvcNetCoreZapatillas/Views/Zapatillas/_ZapatillasPartial.cshtml
@model List<Zapatilla>

<h1>DETALLES ZAPATILLAS PARCIAL</h1>

@foreach (Zapatilla zap in Model)
{
    <div class="card" style="width: 18rem;">
      <div class="card-body">
            <h5 class="card-title">@Model</h5>
            <p class="card-text">@Model.Descripcion</p>
            <h6 class="card-subtitle mb-2 text-muted">@Model.Precio</h6>
        </div>
    </div>
}